//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRestoran_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudzbeStavke
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NarudzbeStavke()
        {
            this.PopustiStavke = new HashSet<PopustiStavke>();
        }
    
        public int NarudzbaStavkaID { get; set; }
        public int NarudzbaID { get; set; }
        public int StavkaMenijaID { get; set; }
        public int Kolicina { get; set; }
        public string Napomena { get; set; }
    
        public virtual Narudzbe Narudzbe { get; set; }
        public virtual StavkeMenija StavkeMenija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopustiStavke> PopustiStavke { get; set; }
    }
}
