//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRestoran_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzbe()
        {
            this.Dostave = new HashSet<Dostave>();
            this.NarudzbeStavke = new HashSet<NarudzbeStavke>();
        }
    
        public int NarudzbaID { get; set; }
        public int KlijentID { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<bool> IsGotovina { get; set; }
        public bool Aktivna { get; set; }
        public bool IsZavrsena { get; set; }
        public Nullable<int> KreditnaKarticaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostave> Dostave { get; set; }
        public virtual Klijenti Klijenti { get; set; }
        public virtual KreditneKartice KreditneKartice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudzbeStavke> NarudzbeStavke { get; set; }
    }
}
