//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRestoran_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopustiStavke
    {
        public int PopustiStavkeID { get; set; }
        public int PopustID { get; set; }
        public int NarudzbaStavkaID { get; set; }
    
        public virtual NarudzbeStavke NarudzbeStavke { get; set; }
        public virtual Popusti Popusti { get; set; }
    }
}
