//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRestoran_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eRestoran_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste aktivirali narudžbu..
        /// </summary>
        internal static string act_order_succ {
            get {
                return ResourceManager.GetString("act_order_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali klijenta..
        /// </summary>
        internal static string add_client_succ {
            get {
                return ResourceManager.GetString("add_client_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali popust..
        /// </summary>
        internal static string add_disc_succ {
            get {
                return ResourceManager.GetString("add_disc_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali artikal..
        /// </summary>
        internal static string add_item_succ {
            get {
                return ResourceManager.GetString("add_item_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali kategoriju..
        /// </summary>
        internal static string add_itemtype_succ {
            get {
                return ResourceManager.GetString("add_itemtype_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali zaposlenika..
        /// </summary>
        internal static string add_usr_succ {
            get {
                return ResourceManager.GetString("add_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa je obavezna..
        /// </summary>
        internal static string address_req {
            get {
                return ResourceManager.GetString("address_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite stavku sa liste..
        /// </summary>
        internal static string cmb_req {
            get {
                return ResourceManager.GetString("cmb_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra je obavezna..
        /// </summary>
        internal static string code_req {
            get {
                return ResourceManager.GetString("code_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum početka ne može biti veći od datuma završetka..
        /// </summary>
        internal static string date_err {
            get {
                return ResourceManager.GetString("date_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali klijenta..
        /// </summary>
        internal static string del_client_succ {
            get {
                return ResourceManager.GetString("del_client_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali popust..
        /// </summary>
        internal static string del_disc_succ {
            get {
                return ResourceManager.GetString("del_disc_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali artikal..
        /// </summary>
        internal static string del_item_succ {
            get {
                return ResourceManager.GetString("del_item_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali kategoriju..
        /// </summary>
        internal static string del_itemtype_succ {
            get {
                return ResourceManager.GetString("del_itemtype_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili klijenta..
        /// </summary>
        internal static string edit_client_succ {
            get {
                return ResourceManager.GetString("edit_client_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće mijenjati popust dok je aktivan..
        /// </summary>
        internal static string edit_disc_err {
            get {
                return ResourceManager.GetString("edit_disc_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili popust..
        /// </summary>
        internal static string edit_disc_succ {
            get {
                return ResourceManager.GetString("edit_disc_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste uredili artikal..
        /// </summary>
        internal static string edit_item_succ {
            get {
                return ResourceManager.GetString("edit_item_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili kategoriju..
        /// </summary>
        internal static string edit_itemtype_succ {
            get {
                return ResourceManager.GetString("edit_itemtype_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste uredili zaposlenika..
        /// </summary>
        internal static string edit_usr_succ {
            get {
                return ResourceManager.GetString("edit_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail nije u ispravnom formatu..
        /// </summary>
        internal static string email_format_err {
            get {
                return ResourceManager.GetString("email_format_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail je obavezan..
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staž nije u ispravnom formatu. Prihvatljive vrijednosti su od 0 do 50..
        /// </summary>
        internal static string exp_err {
            get {
                return ResourceManager.GetString("exp_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staž je obavezan..
        /// </summary>
        internal static string exp_req {
            get {
                return ResourceManager.GetString("exp_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spol nije u ispravnom formatu..
        /// </summary>
        internal static string gender_err {
            get {
                return ResourceManager.GetString("gender_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacija eRestoran je namijenjena zaposlenicima firme za online narudžbu hrane i pića..
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate pravo pristupa..
        /// </summary>
        internal static string login_denied {
            get {
                return ResourceManager.GetString("login_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneseni password je netačan..
        /// </summary>
        internal static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate pravo pristupa ovoj aplikaciji..
        /// </summary>
        internal static string login_restricted {
            get {
                return ResourceManager.GetString("login_restricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste se prijavili..
        /// </summary>
        internal static string login_succ {
            get {
                return ResourceManager.GetString("login_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneseni username ne postoji..
        /// </summary>
        internal static string login_usr_err {
            get {
                return ResourceManager.GetString("login_usr_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno..
        /// </summary>
        internal static string name_req {
            get {
                return ResourceManager.GetString("name_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona mora imati 9 cifara..
        /// </summary>
        internal static string phnum_reg {
            get {
                return ResourceManager.GetString("phnum_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastao je problem sa dodavanjem slike..
        /// </summary>
        internal static string pic_err {
            get {
                return ResourceManager.GetString("pic_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena je obavezna..
        /// </summary>
        internal static string price_req {
            get {
                return ResourceManager.GetString("price_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno..
        /// </summary>
        internal static string sname_req {
            get {
                return ResourceManager.GetString("sname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv je obavezan..
        /// </summary>
        internal static string title_req {
            get {
                return ResourceManager.GetString("title_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime već postoji..
        /// </summary>
        internal static string user_con {
            get {
                return ResourceManager.GetString("user_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora sadržavati najmanje 3 karaktera..
        /// </summary>
        internal static string user_err_length {
            get {
                return ResourceManager.GetString("user_err_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime ne smije sadržavati prazan prostor..
        /// </summary>
        internal static string user_err_space {
            get {
                return ResourceManager.GetString("user_err_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadržavati najmanje 8 karaktera..
        /// </summary>
        internal static string user_pass_format_err {
            get {
                return ResourceManager.GetString("user_pass_format_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezna..
        /// </summary>
        internal static string user_pass_req {
            get {
                return ResourceManager.GetString("user_pass_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesene lozinke se ne poklapaju..
        /// </summary>
        internal static string user_passconf_err {
            get {
                return ResourceManager.GetString("user_passconf_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdite lozinku..
        /// </summary>
        internal static string user_passconf_req {
            get {
                return ResourceManager.GetString("user_passconf_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno..
        /// </summary>
        internal static string user_req {
            get {
                return ResourceManager.GetString("user_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate odabrati najmanje jednu ulogu..
        /// </summary>
        internal static string user_role_err {
            get {
                return ResourceManager.GetString("user_role_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iznos mora biti u opsegu od 0 do 100, isključujući granične vrijednosti..
        /// </summary>
        internal static string val_err {
            get {
                return ResourceManager.GetString("val_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iznos je obavezan..
        /// </summary>
        internal static string val_req {
            get {
                return ResourceManager.GetString("val_req", resourceCulture);
            }
        }
    }
}
